language: java

jdk:
  - oraclejdk8
  
cache:
  directories:
  - $HOME/.gradle

before_install:
 - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
