language: java
sudo: false

jdk:
  - oraclejdk8
  
cache:
  directories:
  - $HOME/.gradle

before_install:
 - chmod +x gradlew

script:
  - ./gradlew check

deploy:
  provider: script
  script:  ./gradlew bintrayUpload -Pbintray_user=$bintray_user -Pbintray_api_key=$bintray_api_key
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
